name: Docker Build CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          echo #FLASHarrow1 | docker login -u reillymeda --password-stdin
          docker build -t reillymeda/jdleecher:latest .
          docker push reillymeda/jdleecher:latest
